### ISSUE TITLE
Symcon Versionsangabe falsch?

### ISSUE THREAD

**Issue by Nall-chan** [symcon/Watchdog#11]
In der Doku und der library.json wird IPS 5.0 angegeben.
Das Modul nutzt aber Attribute, welche laut Symcon Doku erst ab Version 5.1 zur Verfügung stehen.

**Comment by paresy** [comment]
Danke. Fixed mit https://github.com/symcon/Watchdog/commit/81a0e7acb0e4451ac395947272b532f24b3edf29
